
## The output of benchmark.py before Indexing

In [2]:
print("""
============================================================
  StayEase — Query Benchmark
============================================================

>>> EXPLAIN Plans:

  EXPLAIN for 'Portfolio - Room Allocation':
    table=None, type=None, key=None, rows=None, Extra=None

  EXPLAIN for 'Portfolio - Complaints':
    table=c, type=None, key=fk_complaint_member,fk_complaint_type, rows=const, Extra=1
    table=ct, type=None, key=PRIMARY, rows=stayease.c.Complaint_Type_ID, Extra=1    

  EXPLAIN for 'Portfolio - Payments':
    table=p, type=None, key=fk_payment_member,fk_payment_fee, rows=const, Extra=1   
    table=f, type=None, key=PRIMARY, rows=stayease.p.Fee_Type_ID, Extra=1

>>> Timing (100 runs each):
  Portfolio - Room Allocation:
    Avg: 0.3803 ms | Min: 0.2029 ms | Max: 1.1021 ms
  Portfolio - Complaints:
    Avg: 0.4429 ms | Min: 0.1607 ms | Max: 1.7608 ms
  Portfolio - Payments:
    Avg: 0.4084 ms | Min: 0.2173 ms | Max: 1.4973 ms

>>> Summary:
  Query                                 Avg (ms)   Min (ms)   Max (ms)
  --------------------------------------------------------------------
  Portfolio - Room Allocation             0.3803     0.2029     1.1021
  Portfolio - Complaints                  0.4429     0.1607     1.7608
  Portfolio - Payments                    0.4084     0.2173     1.4973

Done.
""")


  StayEase — Query Benchmark

>>> EXPLAIN Plans:

  EXPLAIN for 'Portfolio - Room Allocation':
    table=None, type=None, key=None, rows=None, Extra=None

  EXPLAIN for 'Portfolio - Complaints':
    table=c, type=None, key=fk_complaint_member,fk_complaint_type, rows=const, Extra=1
    table=ct, type=None, key=PRIMARY, rows=stayease.c.Complaint_Type_ID, Extra=1    

  EXPLAIN for 'Portfolio - Payments':
    table=p, type=None, key=fk_payment_member,fk_payment_fee, rows=const, Extra=1   
    table=f, type=None, key=PRIMARY, rows=stayease.p.Fee_Type_ID, Extra=1

>>> Timing (100 runs each):
  Portfolio - Room Allocation:
    Avg: 0.3803 ms | Min: 0.2029 ms | Max: 1.1021 ms
  Portfolio - Complaints:
    Avg: 0.4429 ms | Min: 0.1607 ms | Max: 1.7608 ms
  Portfolio - Payments:
    Avg: 0.4084 ms | Min: 0.2173 ms | Max: 1.4973 ms

>>> Summary:
  Query                                 Avg (ms)   Min (ms)   Max (ms)
  --------------------------------------------------------------------
  Portfol

### StayEase — Query Benchmark (Before Indexing)

### EXPLAIN Plans

**Portfolio - Room Allocation:**
* `table=None`, `type=None`, `key=None`, `rows=None`, `Extra=None`

**Portfolio - Complaints:**
* `table=c`, `type=None`, `key=fk_complaint_member,fk_complaint_type`, `rows=const`, `Extra=1`
* `table=ct`, `type=None`, `key=PRIMARY`, `rows=stayease.c.Complaint_Type_ID`, `Extra=1`

**Portfolio - Payments:**
* `table=p`, `type=None`, `key=fk_payment_member,fk_payment_fee`, `rows=const`, `Extra=1`
* `table=f`, `type=None`, `key=PRIMARY`, `rows=stayease.p.Fee_Type_ID`, `Extra=1`

###  Timing (100 runs each)

* **Portfolio - Room Allocation:** Avg: 0.3803 ms | Min: 0.2029 ms | Max: 1.1021 ms
* **Portfolio - Complaints:** Avg: 0.4429 ms | Min: 0.1607 ms | Max: 1.7608 ms
* **Portfolio - Payments:** Avg: 0.4084 ms | Min: 0.2173 ms | Max: 1.4973 ms

###  Summary

| Query Target | Avg (ms) | Min (ms) | Max (ms) |
| :--- | :--- | :--- | :--- |
| **Portfolio - Room Allocation** | 0.3803 | 0.2029 | 1.1021 |
| **Portfolio - Complaints** | 0.4429 | 0.1607 | 1.7608 |
| **Portfolio - Payments** | 0.4084 | 0.2173 | 1.4973 |#


  ## The output of benchmark.py after Indexing

In [1]:
print("""
============================================================
  StayEase — Query Benchmark
============================================================

>>> EXPLAIN Plans:

  EXPLAIN for 'Portfolio - Room Allocation':
    table=None, type=None, key=None, rows=None, Extra=None

  EXPLAIN for 'Portfolio - Complaints':
    table=c, type=None, key=fk_complaint_member,fk_complaint_type,idx_complaints_member_date, rows=const, Extra=1
    table=ct, type=None, key=PRIMARY, rows=stayease.c.Complaint_Type_ID, Extra=1

  EXPLAIN for 'Portfolio - Payments':
    table=p, type=None, key=fk_payment_member,fk_payment_fee,idx_payments_member_date, rows=const, Extra=1
    table=f, type=None, key=PRIMARY, rows=stayease.p.Fee_Type_ID, Extra=1

>>> Timing (100 runs each):
  Portfolio - Room Allocation:
    Avg: 0.4873 ms | Min: 0.1523 ms | Max: 2.6857 ms
  Portfolio - Complaints:
    Avg: 0.4154 ms | Min: 0.2434 ms | Max: 2.3651 ms
  Portfolio - Payments:
    Avg: 0.3904 ms | Min: 0.2335 ms | Max: 1.0921 ms

>>> Summary:
  Query                                 Avg (ms)   Min (ms)   Max (ms)
  --------------------------------------------------------------------
  Portfolio - Room Allocation             0.4873     0.1523     2.6857
  Portfolio - Complaints                  0.4154     0.2434     2.3651
  Portfolio - Payments                    0.3904     0.2335     1.0921

Done.
""")



  StayEase — Query Benchmark

>>> EXPLAIN Plans:

  EXPLAIN for 'Portfolio - Room Allocation':
    table=None, type=None, key=None, rows=None, Extra=None

  EXPLAIN for 'Portfolio - Complaints':
    table=c, type=None, key=fk_complaint_member,fk_complaint_type,idx_complaints_member_date, rows=const, Extra=1
    table=ct, type=None, key=PRIMARY, rows=stayease.c.Complaint_Type_ID, Extra=1

  EXPLAIN for 'Portfolio - Payments':
    table=p, type=None, key=fk_payment_member,fk_payment_fee,idx_payments_member_date, rows=const, Extra=1
    table=f, type=None, key=PRIMARY, rows=stayease.p.Fee_Type_ID, Extra=1

>>> Timing (100 runs each):
  Portfolio - Room Allocation:
    Avg: 0.4873 ms | Min: 0.1523 ms | Max: 2.6857 ms
  Portfolio - Complaints:
    Avg: 0.4154 ms | Min: 0.2434 ms | Max: 2.3651 ms
  Portfolio - Payments:
    Avg: 0.3904 ms | Min: 0.2335 ms | Max: 1.0921 ms

>>> Summary:
  Query                                 Avg (ms)   Min (ms)   Max (ms)
  ---------------------------------

### StayEase — Query Benchmark (After Indexing)

###  EXPLAIN Plans

**Portfolio - Room Allocation:**
* `table=None`, `type=None`, `key=None`, `rows=None`, `Extra=None`

**Portfolio - Complaints:**
* `table=c`, `type=None`, `key=fk_complaint_member,fk_complaint_type,idx_complaints_member_date`, `rows=const`, `Extra=1`
* `table=ct`, `type=None`, `key=PRIMARY`, `rows=stayease.c.Complaint_Type_ID`, `Extra=1`

**Portfolio - Payments:**
* `table=p`, `type=None`, `key=fk_payment_member,fk_payment_fee,idx_payments_member_date`, `rows=const`, `Extra=1`
* `table=f`, `type=None`, `key=PRIMARY`, `rows=stayease.p.Fee_Type_ID`, `Extra=1`

###  Timing (100 runs each)

* **Portfolio - Room Allocation:** Avg: 0.4873 ms | Min: 0.1523 ms | Max: 2.6857 ms
* **Portfolio - Complaints:** Avg: 0.4154 ms | Min: 0.2434 ms | Max: 2.3651 ms
* **Portfolio - Payments:** Avg: 0.3904 ms | Min: 0.2335 ms | Max: 1.0921 ms

###  Summary

| Query Target | Avg (ms) | Min (ms) | Max (ms) |
| :--- | :--- | :--- | :--- |
| **Portfolio - Room Allocation** | 0.4873 | 0.1523 | 2.6857 |
| **Portfolio - Complaints** | 0.4154 | 0.2434 | 2.3651 |
| **Portfolio - Payments** | 0.3904 | 0.2335 | 1.0921 |